### ISSUE TITLE
[ingest-api] Update neo4j driver to latest 4.4.11

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-api#409]
Bill noticed this error during the `/publish` call on TEST
```
[2023-11-08 21:33:59] ERROR in app: deque.remove(x): x not in deque
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 498, in _send_all
    self.socket.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 498, in _send_all
    self.socket.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 498, in _send_all
    self.socket.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 498, in _send_all
    self.socket.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/src/./app.py", line 819, in publish_datastage
    is_primary = dataset_is_primary(dataset_uuid)
  File "/usr/src/app/src/./app.py", line 2315, in dataset_is_primary
    result = neo_session.run(q).data()
  File "/usr/local/lib/python3.9/site-packages/neo4j/work/simple.py", line 204, in run
    self._connect(self._config.default_access_mode)
  File "/usr/local/lib/python3.9/site-packages/neo4j/work/simple.py", line 108, in _connect
    super()._connect(access_mode)
  File "/usr/local/lib/python3.9/site-packages/neo4j/work/__init__.py", line 79, in _connect
    self._connection = self._pool.acquire(
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 833, in acquire
    return self._acquire(self.address, timeout)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 661, in _acquire
    connection.close()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/_bolt4.py", line 336, in close
    self._send_all()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 500, in _send_all
    self._set_defunct_write(error)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 550, in _set_defunct_write
    self._set_defunct(message, error=error, silent=silent)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 565, in _set_defunct
    self.pool.deactivate(address=self.unresolved_address)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 770, in deactivate
    conn.close()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/_bolt4.py", line 336, in close
    self._send_all()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 500, in _send_all
    self._set_defunct_write(error)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 550, in _set_defunct_write
    self._set_defunct(message, error=error, silent=silent)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 565, in _set_defunct
    self.pool.deactivate(address=self.unresolved_address)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 770, in deactivate
    conn.close()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/_bolt4.py", line 336, in close
    self._send_all()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 500, in _send_all
    self._set_defunct_write(error)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 550, in _set_defunct_write
    self._set_defunct(message, error=error, silent=silent)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 565, in _set_defunct
    self.pool.deactivate(address=self.unresolved_address)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 770, in deactivate
    conn.close()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/_bolt4.py", line 336, in close
    self._send_all()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 500, in _send_all
    self._set_defunct_write(error)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 550, in _set_defunct_write
    self._set_defunct(message, error=error, silent=silent)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 565, in _set_defunct
    self.pool.deactivate(address=self.unresolved_address)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/__init__.py", line 768, in deactivate
    connections.remove(conn)
ValueError: deque.remove(x): x not in deque
[pid: 96|app: 0|req: 285/360] 172.18.0.6 () {66 vars in 1094 bytes} [Wed Nov  8 21:33:58 2023] PUT 
```

The Python neo4j driver fixed such bugs in 4.3 and 4.4
- https://github.com/neo4j/neo4j-python-driver/wiki/4.3-changelog#436
- https://github.com/neo4j/neo4j-python-driver/wiki/4.4-changelog#444

Zhou:
>I verified, the ingest-api, entity-api, and hs-ontology installed neo4j driver neo4j==4.4.0 inside the container. Because in the requirements.txt they all use neo4j==4.4 .
Back in August, we fixed the hs-ontology-api neo4j connection issue but it was something different from this ValueError: deque.remove(x): x not in deque , also connection pool and session related bug. We didn't upgrade to the latest the 4.4.x back then then because the entity-api had been using 4.4.0 and I thought to keep using the same version.
Now looks like we should upgrade to 4.4.11 across the board.

**Comment by yuanzhou** [comment]
Link to https://github.com/hubmapconsortium/devops/issues/100

**Comment by shirey** [comment]
Won't do because we're updating to Neo4j v5
